language: node_js
node_js:
- '5'
deploy:
  provider: heroku
  app: floating-shore-97213
  api_key:
    secure: STs+UKnefDrD6q3CdTCRKhVJCJUCtJOukzi6wUc2Wz092OvE0UJfipa8eYaUg01AOnQDd5wUK0RL2uD+tR9/eICDJPoG8/e6bznImO64kHlAlwAIOB4cP4cXwSjDqaaSMQfsua9HBD7kxY68X2esRJIhzMYRoCJ6Ekf4Z1MmKX9Zx1FtMZyWj+79glESz9HSccqmRWgmndR6NAYpIECVLFcChVLIe+bNwYt9OPEX6eRi3knViU7I2ZoqoVmEVAm6f8HEot5pmGuAEen+fH+x6Am/tYHx2zjAgIIH88+kPG85rvVJlVpbCH0OJOVLSPhu2FkiJUvScrNu5lu3Vd3an8kr3PIp9RngszZ0tJvsCRrWg7+pHb0kWnm1KBEphb1bIi6bqjEbZl7MSHaZFPD4DhsM64DdAzd5RDDWHEuvkNfG0OOps2f62PwTP6v35M8bgGqbhupv3+XXah9gTdImfeEOVm8rluRuVCl52DQSLkaS24KakU72rxqBuRZqnBm1oggrnLOBYG33dlpP34/Dir+COfba0VtxOJnekfGUwpaOKPuX+JMp5M4AWMEJLPczUQGVjpPs4k0IsRKKBhfbt/pjwy6KmpgSfMj1cDfYOAlxDHvn31aF2uPy4qdEEotewFxZZ/xxBVeHKufmWa0wzS1+unV4rRqO1imVNzcARhY=
