FORMAT: 1A
HOST: https://floating-shore-97213.herokuapp.com

# Skills City API

Stacks API is an API to manage Projects, Services and People.

## Hello API [/hello]

### Hello, world! [GET]

+ Response 200

        {"message": "Hello, World!"}

## Hello, buddy! [/hello/{name}]

+ Parameters
    + name: toto (required, string) - name of the person to greet

### Hello, Buddy!  [GET]

+ Response 200

        {"message": "Hello, toto!"}

## Projects Collection [/projects]

### List all Projects [GET]

+ Response 200

        [
            {
                "name": "Refonte Frontal Billetterie",
                "client": "FFT",
                "image_link": "http://cdn/projects/123.png"
            }, {
                "name": "Refonte Home Page",
                "client": "Club Med",
                "image_link": "http://cdn/projects/456.png"
            }, {
                "name": "Refonte Booking Engine",
                "client": "Club Med",
                "image_link": "http://cdn/projects/789.png"
            }
        ]

### Create a new Project [POST]

You may create your own project using this action. It takes a JSON object containing the project name, the client name and an image.

+ project (string) - The project
+ Request

        {
            "name": "Refonte Frontal Billetterie",
            "client": "FFT"
        }

+ Response 201

    + Headers

            Location: /projects/1

    + Body

            {
                "name": "Refonte Frontal Billetterie",
                "client": "FFT",
                "image_link": "http://cdn/projects/123.png"
            }

## Project [/projects/{project_id}]

+ Parameters
    + project_id: 1 (required, number) - ID of the Project in form of an integer

### Get a project [GET]

+ Response 200

        {
            "name": "Refonte Frontal Billetterie",
            "client": "FFT",
            "image_link": "http://cdn/projects/123.png"
        }

### Update a project [PUT]

+ Request

        {
            "name": "New project name",
            "client": "New project client",
        }

+ Response 200

        {
            "name": "New project name",
            "client": "New project client",
            "image_link": "http://cdn/projects/new_logo.png"
        }

### Delete a project [DELETE]

+ Response 204

## Project image [/projects/{project_id}/image]

+ Parameters
    + project_id: 1 (required, number) - ID of the Project in form of an integer

### Upload project image [PUT]

+ Request (multipart/form-data; boundary=---BOUNDARY)

        -----BOUNDARY
        Content-Disposition: form-data; name="image[file]"; filename="image.jpg"
        Content-Type: image/jpeg
        Content-Transfer-Encoding: base64

        /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
        HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
        MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
        AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
        AAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL+AD//Z
        -----BOUNDARY

+ Response 201

        Ok.


## Service Collection [/services]

### List 
