FORMAT: 1A
HOST: https://floating-shore-97213.herokuapp.com

# Skills City API

Stacks API is an API to manage Projects, Services and People.

## Hello API [/hello]

### Hello, world! [GET]

+ Response 200

        {"message": "Hello, World!"}

## Hello, buddy! [/hello/{name}]

+ Parameters
    + name: toto (required, string) - name of the person to greet

### Hello, Buddy!  [GET]

+ Response 200

        {"message": "Hello, toto!"}

## Projects Collection [/projects]

### List all Projects [GET]

+ Response 200

        [
            {
                "name": "Refonte Frontal Billetterie",
                "client": "FFT",
                "logo": "http://cdn/projects/123.png"
            }, {
                "name": "Refonte Home Page",
                "client": "Club Med",
                "logo": "http://cdn/projects/456.png"
            }, {
                "name": "Refonte Booking Engine",
                "client": "Club Med",
                "logo": "http://cdn/projects/789.png"
            }
        ]

### Create a new Project [POST]

You may create your own project using this action. It takes a JSON object containing the project name, the client name and an image.

+ project (string) - The project
+ Request

        {
            "name": "Refonte Frontal Billetterie",
            "client": "FFT"
        }

+ Response 201

    + Headers

            Location: /projects/1

    + Body

            {
                "name": "Refonte Frontal Billetterie",
                "client": "FFT",
                "logo": "http://cdn/projects/123.png"
            }

## Project [/projects/{project_id}]

+ Parameters
    + project_id: 1 (required, number) - ID of the Project in form of an integer

### Get a project [GET]

+ Response 200

        {
            "name": "Refonte Frontal Billetterie",
            "client": "FFT",
            "logo": "http://cdn/projects/123.png"
        }

### Update a project [PUT]

+ Request

        {
            "name": "New project name",
            "client": "New project client",
            "logo": "http://cdn/projects/new_logo.png"
        }

+ Response 200

        {
            "name": "New project name",
            "client": "New project client",
            "logo": "http://cdn/projects/new_logo.png"
        }

### Delete a project [DELETE]

+ Response 204

## Service Collection [/services]

### List 

## People Collection [/people]

### List all People [GET]

+ Response 200

        [
            {
                "nickname": "BAT",
                "firstName": "Bruce",
                "lastName": "Wayne"
            }
        ]

